config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :users, only:[] do
  #   collection do
  #     get :favorites
  #   end
  # end
  
  root "recipes#index"
  get "/other", to: "recipes#other"
  resources :recipes do
    collection do
      get :my
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_one_attached :photo
  validates :title, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private
  def record_not_found
    render file: 'public/404.html', status: 404, layout: false
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_recipe, only: [ :edit, :update, :destroy]
  
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new()
  end

  def show
    # find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def edit
    # find_recipe
    # @recipe= Recipe.find_by(user_id: current_user.id, id: params[:id])
    
  end

  def update
    # find_recipe
    if @recipe.update(clean_params)
      flash["notice"] = '已更新'
      redirect_to root_path
    else
      render :edit
    end
  end

  def other
  end

  def destroy
    @recipe.destroy
    # flash["notice"] = '已刪除'
    redirect_to root_path, notice: '已刪除'
    # find_recipe
  end

  def create
    #strong parameters
    # @recipe = Recipe.new(clean_params)
    # @recipe.user_id = current_user.id

    @recipe = current_user.recipes.new(clean_params)
    if @recipe.save #write to database
      flash["notice"] = '新增成功'
      redirect_to "/"
    else
      render :new # app/views/recipes/new.html #will retain previous data
    end
  end

  def my
    @recipes = current_user.recipes
    render :index
  end

  private
    def clean_params
      params.require(:recipe).permit(:title, :description, :photo)
    end

    def find_recipe
      @recipe = current_user.recipes.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :partial =>'shared/navbar'%> 
    <%= notice %>
    <%= yield %> 
  </body>
</html>

app/views/recipes/_form.html.erb
<%
=begin%>
 <form method="post" action="/recipes">
  <input type="text" name="cc">
  <input type="text" name="dd">
  <input type="text" name="authenticity_token" id="" value="<%= form_authenticity_token %>">
  
  <button type="submit">送出</button>
</form> 
<%
=end%>

<% if recipe.errors.any?%>
  <% recipe.errors.full_messages.each do |msg|%>
  <li><%=msg%></li>
  <%end%>
<%end%>

<%= form_for( recipe ) do |f| %>
  <%= image_tag @recipe.photo.variant(resize_to_limit: [300, 300]) if @recipe.photo.attached?%>
  <div class="field">
    <%= f.label :photo,'照片' %>
    <%= f.file_field (:photo) %>
  </div>
  <div class="field">
    <%= f.label :title,'標題' %>
    <%= f.text_field (:title) %>
  </div>
 
  <div class="field">
    <%= f.label :description,'說明' %>
    <%= f.text_area (:description) %>
  </div>
  <%= f.submit%>
  <% end %>

app/views/recipes/_recipe.html.erb
<div class="card">
    <div class="card-image">
      <figure class="image is-4by3">
      <% if recipe.photo.attached?%>
        <%= image_tag recipe.photo.variant(resize_to_limit: [300, 300]) %>
        <% else %>
        <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
      <%end%> 
      </figure>

    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-left">
          <figure class="image is-48x48">
           <% if recipe.photo.attached?%>
              <%= image_tag recipe.photo.variant(resize_to_limit: [300, 300]) %>
            <% else %>
              <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
            <%end%> 
          </figure>
        </div>
        <div class="media-content">
          <p class="title is-4"><%= recipe.title %></p>
        </div>
         <div class="content">
          <p class="title is-4"> 
            <%if user_signed_in? && recipe.user == current_user%>
            <hr>
             <%= link_to '更新', edit_recipe_path(recipe), class: 'button is-small is-primary'%>/
             <%= link_to '刪除', recipe_path(recipe), method: 'delete', class: 'button is-small is-danger', data: {confirm: '確認刪除？'}%>
             
            <%end%>
          </p>
        </div>
      </div>
    </div>
  </div>

app/views/recipes/edit.html.erb
<h1>編輯食譜</h1>

<%= render 'form', recipe: @recipe%>

app/views/recipes/index.html.erb
<h1>食譜列表</h1>

<%= link_to "新增食譜", new_recipe_path, class: 'button is-danger' %>

<%
=begin%>
 <% @recipes.each do |recipe| %>
 <ul class="home-list"> 
  <li>
    <%= link_to recipe.title, recipe %>
    <%= link_to "修改", edit_recipe_path(recipe), method: 'get' %>
    <%= link_to "刪除", recipe_path(recipe), method: 'delete', data:{confirm: '確定嗎'} %>
  </li> 
 </ul> 
<%end%> 
<%
=end%>
<div class="columns is-multiline">
 <% @recipes.each do |recipe| %>
<div class="column is-3">
  <%= render :partial =>'recipe', :locals => { :recipe => recipe }%>
</div>
 <%end%>
 </div>

app/views/recipes/new.html.erb
<h1>新增食譜</h1>
 
<%= render 'form', recipe: @recipe%>

app/views/recipes/other.erb
<h1>other</h1>

app/views/recipes/show.erb
<h1><%= @recipe.title %></h1>
<h1><%= @recipe.description %></h1>
<%
=begin%>
 <%= image_tag @recipe.photo.variant(resize_to_limit: [300, 300]) if @recipe.photo.attached?%> 
<%
=end%>

 <%= image_tag @recipe.photo.variant(resize: "300x300") if @recipe.photo.attached?%> 

<%= link_to '食品首頁', "/" %>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Home
      </a>

      <a class="navbar-item">
        Documentation
      </a>
      <% if user_signed_in? %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <%= link_to "新增食譜", new_recipe_path, class:'navbar-item'%>
          <%= link_to "我的食譜", my_recipes_path, class:'navbar-item'%>
        </div>
      </div>
      <% end%>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
           <% if user_signed_in? %>
            <%= link_to  "Log Out", destroy_user_session_path, method: 'delete' %>
            <%else%>
              <%= link_to  "Sign up", new_user_registration_path, class: 'button is-primary' %>
              <%= link_to  " Log in", user_session_path, class: 'button is-light' %>
           <% end%>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/welcome/home.html.erb
<h1>Hello!</h1>